"""empty message

Revision ID: 1d17bfa8fe08
Revises: 47a2688bef97
Create Date: 2018-06-14 14:44:13.631207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d17bfa8fe08'
down_revision = '47a2688bef97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_type', sa.Integer(), nullable=True),
    sa.Column('h_count', sa.Integer(), nullable=True),
    sa.Column('seats', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    # ### end Alembic commands ###
