"""empty message

Revision ID: 36faadc21a0f
Revises: 5b2f27493d7e
Create Date: 2018-06-14 15:04:52.941137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36faadc21a0f'
down_revision = '5b2f27493d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('o_user', sa.Integer(), nullable=True),
    sa.Column('o_movie_plan', sa.String(length=128), nullable=True),
    sa.Column('o_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['o_movie_plan'], ['movie_plan.id'], ),
    sa.ForeignKeyConstraint(['o_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_order', sa.Integer(), nullable=True),
    sa.Column('t_seat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['t_order'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('order')
    # ### end Alembic commands ###
