"""empty message

Revision ID: 47a2688bef97
Revises: ed621bc02102
Create Date: 2018-06-13 14:27:04.330971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a2688bef97'
down_revision = 'ed621bc02102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('u_permission', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'u_permission')
    # ### end Alembic commands ###
