"""empty message

Revision ID: 499e77b02fd9
Revises: 8f60416c085c
Create Date: 2018-06-12 14:41:15.802308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499e77b02fd9'
down_revision = '8f60416c085c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinemas', sa.Column('flag', sa.Integer(), nullable=True))
    op.add_column('cinemas', sa.Column('isdelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cinemas', 'isdelete')
    op.drop_column('cinemas', 'flag')
    # ### end Alembic commands ###
