"""empty message

Revision ID: 5b2f27493d7e
Revises: 1d17bfa8fe08
Create Date: 2018-06-14 14:54:29.224338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2f27493d7e'
down_revision = '1d17bfa8fe08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_plan',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('mp_movie', sa.Integer(), nullable=True),
    sa.Column('mp_hall', sa.Integer(), nullable=True),
    sa.Column('mp_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mp_hall'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['mp_movie'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_plan')
    # ### end Alembic commands ###
